const form = document.getElementById('planForm');
const button = document.getElementById('submitBtn');
const statusEl = document.getElementById('status');
const results = document.getElementById('results');

function value(id){ return document.getElementById(id).value; }

form.addEventListener('submit', async (event) => {
  event.preventDefault();
  button.disabled = true;
  button.querySelector('span').textContent = 'Creating your plan...';
  statusEl.textContent = 'Generating';
  try {
    const payload = {
      goal: value('goal'), level: value('level'), age: Number(value('age')),
      equipment: value('equipment'), minutes: Number(value('minutes')),
      days: Number(value('days')), diet: value('diet'), notes: value('notes').trim()
    };
    const response = await fetch('/api/generate-plan', {
      method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify(payload)
    });
    const data = await response.json();
    if (!response.ok) throw new Error(data.detail || 'The server could not create the plan.');
    renderPlan(data);
    statusEl.textContent = 'Ready';
    results.classList.remove('hidden');
    results.scrollIntoView({behavior:'smooth', block:'start'});
  } catch (error) {
    statusEl.textContent = 'Error';
    alert(error.message + '\n\nMake sure the FastAPI server is running.');
  } finally {
    button.disabled = false;
    button.querySelector('span').textContent = 'Generate my plan';
  }
});

document.getElementById('printBtn').addEventListener('click', () => window.print());

function renderPlan(plan){
  document.getElementById('planTitle').textContent = plan.title || 'Your FitBuddy plan';
  document.getElementById('planSummary').textContent = plan.summary || '';
  document.getElementById('source').textContent = plan.source ? `Generated by: ${plan.source}` : '';
  const workouts = document.getElementById('workouts');
  workouts.innerHTML = (plan.workouts || []).map(w => `
    <article class="workout">
      <div class="day">Day ${escapeHtml(w.day)}</div>
      <h3>${escapeHtml(w.title)}</h3>
      <div class="meta">${escapeHtml(w.duration)} minutes · ${escapeHtml(w.focus || 'Training')}</div>
      ${(w.exercises || []).map(e => `<div class="exercise"><b>${escapeHtml(e.name)}</b><span>${escapeHtml(e.sets)} × ${escapeHtml(e.reps)}</span></div>`).join('')}
    </article>`).join('');
  document.getElementById('nutrition').innerHTML = (plan.nutrition || []).map(x => `<li>${escapeHtml(x)}</li>`).join('');
  document.getElementById('recovery').innerHTML = (plan.recovery || []).map(x => `<li>${escapeHtml(x)}</li>`).join('');
}

function escapeHtml(value){
  return String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
}
